### ISSUE TITLE
Unable to build patched glibc even with gcc-7.5.0

### ISSUE THREAD

**Issue by muke101** [efeslab/lapidary#9]
I'm trying to run lapidary for AArch64 on Ubuntu LTS and after installing it gives an error saying it cannot find a library in it's own libc:

`Exception: Could not find any ld.so in /home/l50031074/lapidary/libc/glibc/build/install`

So after running the `clone_and_build.sh` script in `lapidary/libc` I get errors during compilation. The first is that one of the files modified by the patch has an implicit declaration of `memcpy`:

```
../sysdeps/unix/sysv/linux/getentropy.c: In function ‘getPseudoRandomBytes’:
../sysdeps/unix/sysv/linux/getentropy.c:37:5: error: implicit declaration of function ‘memcpy’ [-Werror=implicit-function-declaration]
     memcpy( buffer, &next, copySize );
     ^~~~~~
../sysdeps/unix/sysv/linux/getentropy.c:37:5: error: incompatible implicit declaration of built-in function ‘memcpy’ [-Werror]
../sysdeps/unix/sysv/linux/getentropy.c:37:5: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
```
I fixed this by (naively) adding `#include <string.h>` to the file as suggested. This then compiles fine. 

After fixing this, I get a linking error related to another patched file:

```
/usr/bin/ld: /home/l50031074/lapidary/libc/glibc/build/libc_pic.os: in function `__GI___clock_gettime':
/home/l50031074/lapidary/libc/glibc/rt/../sysdeps/unix/clock_gettime.c:115: undefined reference to `ALWAYS_ONE'
/usr/bin/ld: /home/l50031074/lapidary/libc/glibc/rt/../sysdeps/unix/clock_gettime.c:115: undefined reference to `ALWAYS_ONE'
collect2: error: ld returned 1 exit status
make[2]: *** [../Makerules:699: /home/l50031074/lapidary/libc/glibc/build/libc.so] Error 1
make[2]: Leaving directory '/home/l50031074/lapidary/libc/glibc/elf'
make[1]: *** [Makefile:258: elf/subdir_lib] Error 2
```

I suspect this is bitrot related as presumably this worked back in 2019. I downgraded to gcc-7.5.0 and with this was able to build an unmodified glibc-2.29 just fine. When using it to build the patched glibc in lapidary though I still get the exact same errors as above (including having to fix the memcpy declaration).

Are you guys able to fix this, or is there perhaps a workaround to not having to use a patched glibc at all?

Thanks.

**Comment by muke101** [comment]
Update: I've found that on x86 I can compile the patched glibc in a ubuntu bionic (18.04) container, which also uses gcc 7.5.0. However, the same ubuntu version in a container on an aarch64 machine gets the above errors. Does this give any indication of what's going on?

**Comment by iangneal** [comment]
Hey @muke101,

Just so that we don't keep you waiting on a response from us, it is unlikely that we'll be able to help you resolve this issue any time soon, as we are not actively working on this project at this time. If you do come up with a solution, please feel free to post here or file a PR and we'd be more than happy to review that and merge, but otherwise we just don't have the bandwidth currently to help out with this issue.

All the best, Ian

**Comment by muke101** [comment]
Hey, yea I figured as such but thanks for confirming. Thought it might be worthwhile sharing the details anyway!
